version: 2
defaults: &defaults
  working_directory: /go/src/github.com/pilosa/pdk
  docker:
    - image: circleci/golang:1.10
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: make vendor
      - persist_to_workspace:
          root: vendor
          paths: "*"
  linter:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: vendor
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: go get github.com/remyoudompheng/go-misc/deadcode
      - run: make gometalinter
  test-golang-1.10: &base-test
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: vendor
      - run: make test
  test-golang-1.11-rc:
    <<: *base-test
    docker:
      - image: circleci/golang:1.11-rc
workflows:
  version: 2
  test:
    jobs:
      - build
      - linter:
          requires:
            - build
      - test-golang-1.10:
          requires:
            - linter
      - test-golang-1.11-rc:
          requires:
            - linter
