version: 2
jobs:
  test-golang-1.11: &base-test
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/pilosa/pdk
    steps:
      - checkout
      - run: make test
  test-golang-1.10:
    <<: *base-test
    docker:
      - image: circleci/golang:1.10
workflows:
  version: 2
  test:
    jobs:
      - test-golang-1.10
      - test-golang-1.11
